USE Trobify;

-- Eliminar tablas de la base de datos. El borrado debe seguir este orden para que no haya problemas con las claves ajenas.
DROP TABLE HABITACION;
DROP TABLE EXTRA;
DROP TABLE IMAGEN;
DROP TABLE CONTIENE;
DROP TABLE INMUEBLE;
DROP TABLE ESTADO;
DROP TABLE TIPODEVIVIENDA;
DROP TABLE CARACTERISTICAS;
DROP TABLE UBICACION;
DROP TABLE Provincias;
DROP TABLE FAVORITOS;
DROP TABLE CLIENTE;
DROP TABLE CATALOGO;
DROP TABLE MODALIDAD;
DROP TABLE CERTIFICACIONENERGETICA;
DROP TABLE USUARIO;